"""
Geometric cover — Step 1: candidate rigid tuples in A5 labelled by HQCC.

Enumerates conjugacy classes of A5, searches short tuples (r=3,4) for:
  - product-one representatives
  - generation of A5
  - absolute rigidity (single conjugacy orbit of generating product-one tuples)

Labels classes with HQCC motifs (ternary / flux / period).

Does not construct the cover (Step 2); only cycle-type data + rigidity tests.
"""
from __future__ import annotations

import itertools
import json
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from lib.common import OUT, RESULTS, write_json, write_md  # noqa: E402

# ---------------------------------------------------------------------------
# A5 as even permutations of {0,1,2,3,4}
# ---------------------------------------------------------------------------
def is_even(perm: tuple[int, ...]) -> bool:
    """perm[i] = image of i; return True if even."""
    n = len(perm)
    seen = [False] * n
    cycles = 0
    for i in range(n):
        if not seen[i]:
            cycles += 1
            j = i
            while not seen[j]:
                seen[j] = True
                j = perm[j]
    # sign = (-1)^{n - n_cycles}
    return (n - cycles) % 2 == 0


def compose(p: tuple[int, ...], q: tuple[int, ...]) -> tuple[int, ...]:
    """(p∘q)(i) = p(q(i))."""
    return tuple(p[q[i]] for i in range(len(p)))


def invert(p: tuple[int, ...]) -> tuple[int, ...]:
    inv = [0] * len(p)
    for i, j in enumerate(p):
        inv[j] = i
    return tuple(inv)


def cycle_type(perm: tuple[int, ...]) -> tuple[int, ...]:
    n = len(perm)
    seen = [False] * n
    lengths = []
    for i in range(n):
        if not seen[i]:
            L = 0
            j = i
            while not seen[j]:
                seen[j] = True
                j = perm[j]
                L += 1
            lengths.append(L)
    return tuple(sorted(lengths, reverse=True))


def cycle_type_partition(perm: tuple[int, ...]) -> tuple[int, ...]:
    """Partition of n as usual for Frobenius (omit 1's for display optional)."""
    return cycle_type(perm)


def all_A5() -> list[tuple[int, ...]]:
    elems = []
    for p in itertools.permutations(range(5)):
        if is_even(p):
            elems.append(p)
    return elems


def conjugacy_classes(A5: list[tuple[int, ...]]) -> dict[str, list[tuple[int, ...]]]:
    """
    Partition A5 into conjugacy classes. For A5:
      - id: type 1+1+1+1+1
      - double transp: 2+2+1
      - 3-cycles: 3+1+1  (single class in A5)
      - 5-cycles: split into two classes 5A, 5B (inverses)
    """
    id_perm = (0, 1, 2, 3, 4)
    classes: dict[str, list] = {
        "1A": [id_perm],
        "2A": [],   # double transposition
        "3A": [],   # 3-cycles
        "5A": [],   # one class of 5-cycles
        "5B": [],   # the other
    }
    fives = []
    for g in A5:
        ct = cycle_type(g)
        if ct == (1, 1, 1, 1, 1):
            continue
        if ct == (2, 2, 1):
            classes["2A"].append(g)
        elif ct == (3, 1, 1):
            classes["3A"].append(g)
        elif ct == (5,):
            fives.append(g)

    # Split 5-cycles: g ~ h in A5 iff h = x g x^{-1} for even x.
    # Two classes: take orbit of one 5-cycle under conjugation by A5.
    if fives:
        g0 = fives[0]
        orbit = set()
        for x in A5:
            # x g0 x^{-1}
            xi = invert(x)
            conj = compose(compose(x, g0), xi)
            orbit.add(conj)
        for g in fives:
            if g in orbit:
                classes["5A"].append(g)
            else:
                classes["5B"].append(g)
    return classes


# HQCC labels for classes
HQCC_LABEL = {
    "1A": "unramified / identity",
    "2A": "T-complementarity / flux involution (type 2+2+1)",
    "3A": "ternary branch / Z/3 / n↦n/3 or Ad residue (type 3+1+1)",
    "5A": "period / pentagonal sector — 5-cycle class A (use sparingly)",
    "5B": "period / pentagonal sector — 5-cycle class B (inverse class)",
}


def generate_A5_from(gens: list[tuple[int, ...]]) -> set[tuple[int, ...]]:
    """Subgroup of S5 generated by gens (BFS on left multiplication)."""
    from collections import deque

    idp = (0, 1, 2, 3, 4)
    S = list(gens) + [invert(g) for g in gens]
    group = {idp}
    q = deque([idp])
    while q:
        g = q.popleft()
        for s in S:
            h = compose(g, s)
            if h not in group:
                group.add(h)
                q.append(h)
        if len(group) >= 60:
            break
    return group


def product(perms: list[tuple[int, ...]]) -> tuple[int, ...]:
    r = (0, 1, 2, 3, 4)
    for p in perms:
        r = compose(r, p)
    return r


def is_identity(p: tuple[int, ...]) -> bool:
    return p == (0, 1, 2, 3, 4)


def conjugate_tuple(x: tuple[int, ...], tup: tuple[tuple[int, ...], ...]) -> tuple:
    xi = invert(x)
    return tuple(compose(compose(x, g), xi) for g in tup)


def count_conjugacy_orbits(
    A5: list[tuple[int, ...]],
    representatives: list[tuple[tuple[int, ...], ...]],
    max_reps: int = 2000,
) -> int:
    """Number of A5-conjugacy orbits among product-one generating tuples."""
    unused = list(representatives[:max_reps])
    orbits = 0
    while unused:
        base = unused.pop()
        orbits += 1
        orbit = {conjugate_tuple(x, base) for x in A5}
        # also braid? absolute rigidity = single conjugacy orbit only
        unused = [t for t in unused if t not in orbit]
        if orbits > 20:
            # too many — not rigid; stop counting precisely
            return orbits + (1 if unused else 0)
    return orbits


def search_tuples(
    classes: dict[str, list],
    A5: list[tuple[int, ...]],
    signature: list[str],
    max_checks: int = 80000,
) -> dict:
    """
    Search product-one generating tuples of given class signature.
    signature e.g. ['2A','3A','5A']
    """
    pools = [classes[name] for name in signature]
    sizes = [len(p) for p in pools]
    total = 1
    for s in sizes:
        total *= s

    found_prod = []
    checked = 0
    # smart search: fix first r-1 randomly/product, solve last if r small
    # For r=3: g*h*k=1 ⇒ k = (g h)^{-1}, check k in last class
    r = len(signature)
    if r == 3:
        C0, C1, C2 = pools
        set2 = set(C2)
        for g in C0:
            for h in C1:
                checked += 1
                if checked > max_checks:
                    break
                k = invert(compose(g, h))
                if k in set2:
                    found_prod.append((g, h, k))
            if checked > max_checks:
                break
    elif r == 4:
        C0, C1, C2, C3 = pools
        set3 = set(C3)
        for g in C0:
            for h in C1:
                for k in C2:
                    checked += 1
                    if checked > max_checks:
                        break
                    m = invert(product([g, h, k]))
                    if m in set3:
                        found_prod.append((g, h, k, m))
                if checked > max_checks:
                    break
            if checked > max_checks:
                break
    else:
        return {"signature": signature, "error": "r not in {3,4}"}

    # generation filter
    generating = []
    for tup in found_prod:
        G = generate_A5_from(list(tup))
        if len(G) == 60:
            generating.append(tup)

    # rigidity: count conjugacy orbits among generating product-one tuples
    # subsample if huge
    sample = generating[:500]
    n_orbits = None
    if sample:
        n_orbits = count_conjugacy_orbits(A5, sample, max_reps=min(300, len(sample)))

    # braid dimension heuristic (classical):
    # for center-free G, dim ≈ sum (dim class_i) - (r-2)(|G|-1) ... use simple:
    # absolute rigid if exactly one conjugacy class of such tuples
    rigid = (n_orbits == 1) if n_orbits is not None else None

    # HQCC score: prefer more 3A, fewer 5A/5B
    n3 = signature.count("3A")
    n5 = signature.count("5A") + signature.count("5B")
    n2 = signature.count("2A")
    hqcc_score = 10 * n3 + 3 * n2 - 2 * n5

    return {
        "signature": signature,
        "class_sizes": sizes,
        "cartesian_total": total,
        "checked": checked,
        "n_product_one": len(found_prod),
        "n_generating_A5": len(generating),
        "n_conjugacy_orbits_sample": n_orbits,
        "absolutely_rigid_heuristic": rigid,
        "hqcc_score": hqcc_score,
        "hqcc_labels": [HQCC_LABEL[s] for s in signature],
        "sample_tuple_cycle_types": [
            [cycle_type(g) for g in tup] for tup in generating[:3]
        ],
    }


def classical_candidates() -> list[list[str]]:
    """
    Standard short signatures involving 3-cycles for A5 monodromy.
    """
    return [
        # Classical icosahedral-type
        ["2A", "3A", "5A"],
        ["2A", "3A", "5B"],
        ["3A", "3A", "5A"],
        ["3A", "3A", "5B"],
        ["2A", "2A", "3A"],  # may generate smaller
        ["3A", "3A", "3A"],  # three 3-cycles
        # Four branch points — more ternary
        ["3A", "3A", "3A", "2A"],
        ["3A", "3A", "3A", "3A"],
        ["2A", "2A", "3A", "3A"],
        ["2A", "3A", "3A", "3A"],
        ["2A", "3A", "5A", "5B"],  # often used
        ["3A", "3A", "2A", "5A"],
        ["3A", "3A", "5A", "5B"],
    ]


def main():
    t0 = time.time()
    print("GEOMETRIC STEP 1 — rigid A5 tuples + HQCC labels", flush=True)
    A5 = all_A5()
    print(f"  |A5| = {len(A5)}", flush=True)
    assert len(A5) == 60
    classes = conjugacy_classes(A5)
    class_info = {k: len(v) for k, v in classes.items()}
    print(f"  class sizes: {class_info}", flush=True)
    # sanity: 1+15+20+12+12 = 60
    assert sum(class_info.values()) == 60, class_info

    results = []
    for sig in classical_candidates():
        print(f"  testing signature {sig} ...", flush=True)
        rec = search_tuples(classes, A5, sig)
        results.append(rec)
        print(
            f"    prod1={rec.get('n_product_one')} genA5={rec.get('n_generating_A5')} "
            f"orbits~{rec.get('n_conjugacy_orbits_sample')} rigid={rec.get('absolutely_rigid_heuristic')} "
            f"hqcc_score={rec.get('hqcc_score')}",
            flush=True,
        )

    # Rank by: rigid first, then generating>0, then hqcc_score
    def rank_key(r):
        rigid = r.get("absolutely_rigid_heuristic") is True
        gen = r.get("n_generating_A5") or 0
        return (
            0 if rigid else 1,
            0 if gen > 0 else 1,
            -r.get("hqcc_score", 0),
            -(gen),
        )

    ranked = sorted(results, key=rank_key)

    # Explicit check of classical (2,3,5) known rigid
    note_235 = (
        "The signature (2A,3A,5A) is the classical icosahedral triple for A5; "
        "it is absolutely rigid in the literature. Our conjugacy-orbit heuristic "
        "should find a single orbit when sampling is complete."
    )

    # Write documentation
    lines = [
        "# Geometric cover — Step 1: candidate rigid tuples in \(A_5\)",
        "",
        f"_Elapsed: {round(time.time()-t0, 2)}s_",
        "",
        "## Goal",
        "",
        "List conjugacy-class tuples in \(A_5\) that:",
        "1. admit product-one representatives generating \(A_5\);",
        "2. are (heuristically) absolutely rigid;",
        "3. can be **labelled** by HQCC ternary / flux / period motifs.",
        "",
        "Cover construction (Step 2) is **not** performed here.",
        "",
        "---",
        "",
        "## Conjugacy classes of \(A_5\)",
        "",
        "| Class | Size | Cycle type | HQCC label |",
        "|-------|-----:|------------|------------|",
    ]
    ct_map = {
        "1A": "1+1+1+1+1",
        "2A": "2+2+1",
        "3A": "3+1+1",
        "5A": "5",
        "5B": "5 (inverse class)",
    }
    for name in ["1A", "2A", "3A", "5A", "5B"]:
        lines.append(
            f"| {name} | {class_info[name]} | {ct_map[name]} | {HQCC_LABEL[name]} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Candidate signatures (ranked)",
        "",
        "| Signature | prod-1 | gen \(A_5\) | conj. orbits (sample) | abs. rigid? | HQCC score |",
        "|-----------|-------:|----------:|----------------------:|:-----------:|-----------:|",
    ]
    for r in ranked:
        sig = ",".join(r["signature"])
        lines.append(
            f"| `({sig})` | {r.get('n_product_one')} | {r.get('n_generating_A5')} | "
            f"{r.get('n_conjugacy_orbits_sample')} | {r.get('absolutely_rigid_heuristic')} | "
            f"{r.get('hqcc_score')} |"
        )

    lines += [
        "",
        "### HQCC labelling of top candidates",
        "",
    ]
    for r in ranked[:8]:
        sig = ",".join(r["signature"])
        lines.append(f"#### `({sig})`")
        lines.append(f"- HQCC score: **{r.get('hqcc_score')}**")
        lines.append(f"- gen \(A_5\): {r.get('n_generating_A5')}, rigid≈{r.get('absolutely_rigid_heuristic')}")
        for lab in r.get("hqcc_labels") or []:
            lines.append(f"  - {lab}")
        if r.get("sample_tuple_cycle_types"):
            lines.append(f"- sample cycle types: `{r['sample_tuple_cycle_types'][:2]}`")
        lines.append("")

    lines += [
        "---",
        "",
        "## Interpretation for HQCC-nativeness",
        "",
        "### Preferred (ternary-heavy)",
        "",
        "- Signatures with **multiple 3A** factors match the ternary / HQCC branch motif.",
        "- `(3A,3A,3A,2A)` and `(3A,3A,3A,3A)` maximise ternary content; rigidity must be checked carefully",
        "  (four branch points → Hurwitz space may be positive-dimensional → families, not a single cover).",
        "",
        "### Classical rigid (known)",
        "",
        f"- `(2A,3A,5A)` / `(2A,3A,5B)`: {note_235}",
        "- HQCC labelling is **mixed**: one ternary (3A), one flux involution (2A), one period-like 5-cycle.",
        "- Geometrically standard (icosahedral); **nativeness** requires Step 4 (express branch data via \(\\{n/3,3n\\pm1\\}\)),",
        "  not only abstract cycle types.",
        "",
        "### Tension with arithmetic programme",
        "",
        "- Pure 5-cycle emphasis risks \(D_5\)-type specialisations (G4 Heavy lesson).",
        "- Arithmetic HQCC **seeds** already force 3-cycles via the operational criterion;",
        "  geometry should **not** drop the ternary class.",
        "",
        "---",
        "",
        "## Recommended tuples for Step 2",
        "",
    ]

    # Build recommendations
    recs = []
    for r in ranked:
        if (r.get("n_generating_A5") or 0) <= 0:
            continue
        sig = r["signature"]
        if r.get("absolutely_rigid_heuristic") is True:
            recs.append((sig, "absolutely rigid (heuristic)", r))
        elif r.get("n_conjugacy_orbits_sample") == 1:
            recs.append((sig, "single conjugacy orbit in sample", r))
        elif len(sig) == 3 and "3A" in sig and (r.get("n_generating_A5") or 0) > 0:
            recs.append((sig, "classical short triple with ternary", r))

    if not recs:
        # fallback: any generating
        for r in ranked:
            if (r.get("n_generating_A5") or 0) > 0:
                recs.append((r["signature"], "generates A5 (rigidity open)", r))

    for i, (sig, why, r) in enumerate(recs[:6], 1):
        lines.append(f"{i}. **`({','.join(sig)})`** — {why}; HQCC score {r.get('hqcc_score')}.")
    lines += [
        "",
        "### Immediate Step 2 options",
        "",
        "1. **Classical path:** realise `(2A,3A,5A)` as the icosahedral cover / Belyi map over \(\\mathbb{Q}(t)\)",
        "   (known existence); then attempt Step 4 HQCC labelling of branch points.",
        "2. **Ternary path:** if a rigid (or 0-dim braid orbit) multi-`3A` signature exists, construct its",
        "   Hurwitz cover preferentially — better HQCC narrative.",
        "3. **Computational:** Magma/GAP `HurwitzClassNumber` / braid orbit routines for signatures",
        "   marked rigid=False but gen>0 (may still have rational points).",
        "",
        "---",
        "",
        "## What Step 1 does *not* claim",
        "",
        "- No geometric monodromy proof yet (needs cover in Step 2).",
        "- No automatic compatibility with HQCC seeds \(x^5-55x+88\), etc. (Step 3).",
        "- No closed form in \(\\xi=2\\cos(2\\pi/539.9)\).",
        "",
        "---",
        "",
        "## Raw results",
        "",
        "```json",
        json.dumps(
            [{k: v for k, v in r.items() if k != "sample_tuple_cycle_types" or True} for r in ranked],
            indent=2,
            default=str,
        )[:4000],
        "```",
        "",
        "_Generated by geometric_step1.py_",
    ]

    doc = "\n".join(lines)
    write_md(OUT / "GEOMETRIC_STEP1.md", doc)
    write_md(RESULTS / "GEOMETRIC_STEP1.md", doc)
    write_md(ROOT / "GEOMETRIC_STEP1.md", doc)
    write_json(
        OUT / "GEOMETRIC_STEP1.json",
        {
            "elapsed_sec": round(time.time() - t0, 2),
            "class_sizes": class_info,
            "results": ranked,
            "hqcc_labels": HQCC_LABEL,
        },
    )
    print(f"Wrote GEOMETRIC_STEP1.md in {time.time()-t0:.1f}s", flush=True)


if __name__ == "__main__":
    main()
