"""
Direction 2 — Resonant monoid / saturation of L_0
Direction 3 — First cut: unify PE ↔ B avatars on L_0

Dir 2:
  - Multiplicative monoid M generated by {3,61,80,243,539} (+ optional 9=3^2)
  - Extended monoid with short additive catalogue sums
  - Saturation vs 3-smooth integers; residue classes of k and A mod 3^m
  - Compare monoid elements to B-embed irr / A5 sets

Dir 3:
  - Search for maps Φ linking PE (α,β,k,m) to B-parameter A
  - Candidates: A=α, A=β, A=α+β, A=α-β, A=k*scale, A from disc data
  - Paths on pure-even envelope that hit B-family shapes (Tschirnhaus?)
  - Lattice points meaningful in both pictures

Output: L0_MONOID_SATURATION.md, L0_PE_B_UNIFY.md, L0_MONOID_PE_B.json
"""
from __future__ import annotations

import math
import sys
import time
from collections import Counter, defaultdict
from fractions import Fraction
from pathlib import Path

import sympy as sp

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from lib.common import (  # noqa: E402
    MODEL_CORE,
    OUT,
    RESULTS,
    classify_poly,
    is_square,
    write_json,
    write_md,
    x,
)
from lib.lemmas import disc_bj_int  # noqa: E402

# ---------------------------------------------------------------------------
# Monoid generators
# ---------------------------------------------------------------------------

GEN_MULT = (3, 61, 80, 243, 539)  # primary resonant generators
GEN_MULT_EXT = GEN_MULT + (9, 27)  # include pure 3-powers already in 3*
ADD_PAIRS = [
    (61, 27),  # 88 flagship-ish
    (61, 19),  # if used
    (80, 8),
    (3, 1),
    (61, 3),
    (80, 3),
    (539, 1),
    (61, 27),  # 88
    (55, 33),  # skip if not gens
]


def monoid_multiplicative(gens, max_n: int = 50000, max_elems: int = 5000) -> set[int]:
    """Monoid generated by gens under multiplication, truncated by size."""
    M = {1}
    changed = True
    while changed and len(M) < max_elems:
        changed = False
        add = set()
        for m in M:
            for g in gens:
                p = m * g
                if p <= max_n and p not in M:
                    add.add(p)
        if add:
            M |= add
            changed = True
    return M


def monoid_with_additive(M_mult: set[int], max_n: int = 50000, rounds: int = 3) -> set[int]:
    """
    Close under selected short sums: if a,b in monoid (or gens), allow a+b if ≤ max_n,
    then re-multiply a few rounds (saturation under catalogue-style sums).
    """
    M = set(M_mult)
    gens = set(GEN_MULT_EXT) | {1}
    for _ in range(rounds):
        base = list(M | gens)
        new = set()
        # all pairs of small elements
        small = [a for a in base if a <= 2000]
        for i, a in enumerate(small):
            for b in small[i:]:
                s = a + b
                if s <= max_n:
                    new.add(s)
        # named additive pairs from catalogue
        for a, b in [(61, 27), (61, 3), (80, 3), (80, 8), (539, 1), (3, 6), (9, 9)]:
            if a + b <= max_n:
                new.add(a + b)
        # multiply new by gens
        grow = set()
        for n in new:
            if n not in M:
                grow.add(n)
            for g in GEN_MULT:
                p = n * g
                if p <= max_n:
                    grow.add(p)
        if not grow - M:
            M |= new
            break
        M |= grow
    return M


def is_3_smooth(n: int) -> bool:
    if n <= 0:
        return False
    while n % 3 == 0:
        n //= 3
    return n == 1


def is_3_smooth_times_S(n: int, S=(61, 80, 539)) -> bool:
    """n = 3^a * product S-powers."""
    if n <= 0:
        return False
    n = abs(n)
    for p in (3,) + tuple(S):
        while n % p == 0:
            n //= p
    return n == 1


def factor_resonant(n: int) -> dict:
    """Factor using resonant primes {2,3,5,61,80→16*5, 539→7*7*11} carefully."""
    # Use ordinary factorint
    return dict(sp.factorint(abs(int(n)))) if n else {}


# ---------------------------------------------------------------------------
# B-family and PE helpers
# ---------------------------------------------------------------------------

PE_K = {
    "flagship": Fraction(-8, 5),
    "classical": Fraction(4, 5),
    "lsw": Fraction(-4),
    "s12": Fraction(-12, 5),
    "s16": Fraction(-16, 5),
    "flag_flip": Fraction(8, 5),
    "class_flip": Fraction(-4, 5),
}


def pure_even_ab(m: Fraction, k: Fraction):
    al = 256 * m**2 - Fraction(3125) * k**4 / 256
    return al, k * al


def clear_bj(al: Fraction, be: Fraction):
    if al == 0:
        return None
    ar, br = Fraction(al), Fraction(be)
    D = int(sp.ilcm(ar.denominator, br.denominator))
    return int(ar * D**4), int(br * D**5)


def B_status(A: int, do_gal: bool = False) -> dict:
    chi = x**5 + 75 * x**3 + A * x**2 + 3 * A
    pol = sp.Poly(chi, x, domain=sp.ZZ)
    if not pol.is_irreducible:
        return {"A": A, "irr": False, "disc_sq": False, "gal": "red"}
    disc = int(pol.discriminant())
    sq = disc > 0 and is_square(disc)
    gal = "even"
    if do_gal and sq:
        cl = classify_poly(chi, do_galois=True)
        st = str(cl.get("status") or "")
        g = str(cl.get("galois") or "")
        if st.startswith("HIT_A5") or "A5" in g:
            gal = "A5"
        elif "D5" in g:
            gal = "D5"
        else:
            gal = "even_other"
    return {"A": A, "irr": True, "disc_sq": sq, "gal": gal, "disc": disc}


# ---------------------------------------------------------------------------
# Direction 2
# ---------------------------------------------------------------------------


def direction_2() -> dict:
    print("DIRECTION 2 — monoid / saturation", flush=True)
    max_n = 30000
    M0 = monoid_multiplicative(GEN_MULT, max_n=max_n)
    M1 = monoid_multiplicative(GEN_MULT_EXT, max_n=max_n)
    M2 = monoid_with_additive(M0, max_n=max_n, rounds=2)
    print(f"  |M_mult|={len(M0)} |M_ext|={len(M1)} |M_add|={len(M2)}", flush=True)

    # 3-smooth integers up to bound
    smooth3 = []
    p = 1
    while p <= max_n:
        smooth3.append(p)
        p *= 3
    # also 3^a up to max

    # Saturation: which 3-smooth are in monoid?
    hit_smooth = [s for s in smooth3 if s in M2 or s in M0]
    miss_smooth = [s for s in smooth3 if s not in M2]

    # Resonant-smooth: 3^a * 61^b * 80^c * 243^d * 539^e
    # Count how many ≤ max_n lie in pure mult monoid (should be all of M0)
    def enum_resonant_smooth(max_n):
        out = set()
        # 80=16*5=2^4*5, 539=7^2*11 — so mult monoid is NOT 3-smooth
        # "resonant smooth" = only primes dividing some generator
        primes_allowed = set()
        for g in GEN_MULT:
            primes_allowed |= set(sp.factorint(g))
        # generate all products
        # recursive
        from functools import lru_cache

        gens_pf = [dict(sp.factorint(g)) for g in GEN_MULT]

        def rec(i, cur):
            if cur > max_n:
                return
            if i == len(GEN_MULT):
                out.add(cur)
                return
            g = GEN_MULT[i]
            pwr = 1
            while cur * pwr <= max_n:
                rec(i + 1, cur * pwr)
                if pwr > max_n // g:
                    break
                pwr *= g

        rec(0, 1)
        return out

    Rsmooth = enum_resonant_smooth(max_n)
    print(f"  resonant-smooth count ≤{max_n}: {len(Rsmooth)}", flush=True)
    # M0 should equal Rsmooth if monoid is free products of gens
    # Actually monoid from gens is exactly products of gens = resonant mult set
    missing_from_M0 = sorted(Rsmooth - M0)[:20]
    extra_M0 = sorted(M0 - Rsmooth)[:20]

    # Residue classes of monoid mod 3^m
    res_mod = {}
    for m in (1, 2, 3, 4, 5):
        mod = 3**m
        classes = sorted({n % mod for n in M2 if n > 0})
        res_mod[m] = {
            "mod": mod,
            "n_classes": len(classes),
            "classes_sample": classes[:40],
            "density_proxy": len(classes) / mod,
        }

    # k residues for PE catalogue
    k_res = {}
    for m in (1, 2, 3, 4):
        mod = 3**m
        # k as rational - look at num, den mod
        classes = set()
        for name, k in PE_K.items():
            # store k mod via (num * inv den) if den invertible
            num, den = k.numerator, k.denominator
            if math.gcd(den, mod) == 1:
                inv = pow(den % mod, -1, mod)
                classes.add((num * inv) % mod)
            else:
                classes.add(f"den_not_inv:{k}")
        k_res[m] = list(classes)

    # A residues for B: A in ±M2 sample
    A_pool = sorted(M2)[:500] + sorted({-n for n in list(M2)[:200]})
    A_mod = {}
    for m in (1, 2, 3, 4):
        mod = 3**m
        A_mod[m] = sorted({a % mod for a in A_pool})

    # B-embed on monoid elements: irr / A5 rate
    print("  B-status on monoid sample...", flush=True)
    B_on_M = []
    n_gal = 0
    sample_M = sorted(M2)[:80] + [3, 9, 27, 61, 80, 243, 539, 88, 4880]
    sample_M = sorted(set(sample_M))
    for A in sample_M:
        if A == 0:
            continue
        do_gal = n_gal < 25 and A in set(GEN_MULT) | {9, 27, 88, 243, 539, 4880, 18, 54}
        st = B_status(A, do_gal=do_gal)
        if do_gal:
            n_gal += 1
        st["in_M0"] = A in M0
        st["in_M2"] = A in M2
        st["resonant_smooth"] = A in Rsmooth
        B_on_M.append(st)
        # also -A
        stn = B_status(-A, do_gal=False)
        stn["in_M0"] = False
        stn["in_M2"] = False
        stn["sign"] = -1
        B_on_M.append(stn)

    irr_rate = sum(1 for r in B_on_M if r["irr"]) / max(len(B_on_M), 1)
    a5_checked = [r for r in B_on_M if r["gal"] == "A5"]

    # PE specialisations: which |α|,|β| land in monoid?
    print("  PE coeffs vs monoid...", flush=True)
    pe_hits = []
    M_list = M2
    for name, k in PE_K.items():
        for mv in [
            Fraction(1, 8),
            Fraction(5, 8),
            Fraction(5, 4),
            Fraction(1, 5),
            Fraction(1, 1),
            Fraction(-5, 8),
        ]:
            al, be = pure_even_ab(mv, k)
            cl = clear_bj(al, be)
            if not cl:
                continue
            A, B = cl
            pe_hits.append(
                {
                    "name": name,
                    "k": str(k),
                    "m": str(mv),
                    "alpha": A,
                    "beta": B,
                    "abs_alpha_in_M2": abs(A) in M_list,
                    "abs_beta_in_M2": abs(B) in M_list,
                    "abs_alpha_in_M0": abs(A) in M0,
                    "abs_beta_in_M0": abs(B) in M0,
                }
            )

    n_alpha_M2 = sum(1 for r in pe_hits if r["abs_alpha_in_M2"])
    n_beta_M2 = sum(1 for r in pe_hits if r["abs_beta_in_M2"])

    # Forbidden residues: mod 9, which classes never appear for irr B with A in 1..N?
    print("  residue survey A=1..500 for B irr...", flush=True)
    mod9_irr = Counter()
    mod9_all = Counter()
    mod27_irr = Counter()
    for A in range(-200, 201):
        if A == 0:
            continue
        mod9_all[A % 9] += 1
        st = B_status(A, do_gal=False)
        if st["irr"]:
            mod9_irr[A % 9] += 1
            mod27_irr[A % 27] += 1
    # classes with zero irr in range
    empty_mod9 = [r for r in range(9) if mod9_irr[r] == 0]

    return {
        "generators_mult": list(GEN_MULT),
        "generators_ext": list(GEN_MULT_EXT),
        "sizes": {"M0_mult": len(M0), "M1_ext": len(M1), "M2_add": len(M2), "Rsmooth": len(Rsmooth)},
        "M0_sample": sorted(M0)[:40],
        "M2_sample": sorted(M2)[:40],
        "M2_not_M0_sample": sorted(M2 - M0)[:30],
        "3smooth_hit": hit_smooth,
        "3smooth_miss": miss_smooth,
        "missing_Rsmooth_from_M0": missing_from_M0,
        "extra_M0": extra_M0,
        "res_mod_3m": res_mod,
        "k_residues": k_res,
        "A_residues_monoid": {str(m): v[:20] for m, v in A_mod.items()},
        "B_on_monoid": B_on_M,
        "B_irr_rate_on_sample": irr_rate,
        "B_A5_on_sample": a5_checked,
        "PE_vs_monoid": pe_hits,
        "PE_alpha_in_M2": n_alpha_M2,
        "PE_beta_in_M2": n_beta_M2,
        "PE_n": len(pe_hits),
        "mod9_irr_counts": dict(mod9_irr),
        "mod9_empty_irr": empty_mod9,
        "mod27_irr_top": mod27_irr.most_common(15),
    }


# ---------------------------------------------------------------------------
# Direction 3 — unify PE ↔ B
# ---------------------------------------------------------------------------


def direction_3(d2: dict) -> dict:
    print("DIRECTION 3 — PE ↔ B unify (first cut)", flush=True)
    # Build PE fibre list with Z coeffs
    pe_fibres = []
    for name, k in PE_K.items():
        for mv in [
            Fraction(1, 8),
            Fraction(5, 8),
            Fraction(5, 4),
            Fraction(1, 5),
            Fraction(1, 4),
            Fraction(3, 8),
            Fraction(1, 1),
            Fraction(-1, 8),
            Fraction(-5, 8),
            Fraction(-5, 4),
        ]:
            al, be = pure_even_ab(mv, k)
            cl = clear_bj(al, be)
            if not cl:
                continue
            A, B = cl
            pe_fibres.append(
                {
                    "name": name,
                    "k": str(k),
                    "k_frac": k,
                    "m": str(mv),
                    "alpha": A,
                    "beta": B,
                    "disc": disc_bj_int(A, B) if abs(A) < 10**8 and abs(B) < 10**8 else None,
                }
            )

    # Candidate maps Φ: PE → A
    maps = {
        "A=alpha": lambda r: r["alpha"],
        "A=beta": lambda r: r["beta"],
        "A=-alpha": lambda r: -r["alpha"],
        "A=-beta": lambda r: -r["beta"],
        "A=alpha+beta": lambda r: r["alpha"] + r["beta"],
        "A=alpha-beta": lambda r: r["alpha"] - r["beta"],
        "A=beta-alpha": lambda r: r["beta"] - r["alpha"],
        "A=gcd": lambda r: int(math.gcd(abs(r["alpha"]), abs(r["beta"]))) or None,
        "A=k_num*k_den": lambda r: r["k_frac"].numerator * r["k_frac"].denominator,
        "A=round(alpha/k)": lambda r: (
            int(round(r["alpha"] / float(r["k_frac"]))) if r["k_frac"] != 0 else None
        ),
    }

    map_results = {}
    for mname, fn in maps.items():
        hits = []
        n_ok = 0
        n_A5 = 0
        n_try = 0
        for r in pe_fibres:
            try:
                A = fn(r)
            except Exception:
                continue
            if A is None or A == 0:
                continue
            if abs(A) > 10**7:
                continue
            n_try += 1
            st = B_status(int(A), do_gal=(n_A5 + n_ok < 30 and abs(A) < 50000))
            if st["irr"] and st["disc_sq"]:
                n_ok += 1
            if st["gal"] == "A5":
                n_A5 += 1
                hits.append(
                    {
                        "pe": f"{r['name']}:m={r['m']}",
                        "k": r["k"],
                        "alpha": r["alpha"],
                        "beta": r["beta"],
                        "A": int(A),
                        "gal": st["gal"],
                    }
                )
            elif st["irr"] and len(hits) < 5:
                hits.append(
                    {
                        "pe": f"{r['name']}:m={r['m']}",
                        "A": int(A),
                        "gal": st["gal"],
                        "irr": st["irr"],
                    }
                )
        map_results[mname] = {
            "n_try": n_try,
            "n_irr_even": n_ok,
            "n_A5": n_A5,
            "hit_rate_even": n_ok / max(n_try, 1),
            "samples": hits[:12],
        }
        print(
            f"  map {mname}: try={n_try} even={n_ok} A5={n_A5}",
            flush=True,
        )

    # Reverse: B A in monoid → does there exist PE fibre with α or β = A?
    pe_abs = set()
    for r in pe_fibres:
        pe_abs.add(r["alpha"])
        pe_abs.add(r["beta"])
        pe_abs.add(-r["alpha"])
        pe_abs.add(-r["beta"])

    M2 = set(d2.get("M2_sample") or [])
    # rebuild larger M2 from d2 sizes - use monoid again
    M2_full = monoid_with_additive(
        monoid_multiplicative(GEN_MULT, max_n=20000), max_n=20000, rounds=2
    )
    reverse_hits = []
    for A in sorted(M2_full)[:100]:
        st = B_status(A, do_gal=False)
        if not st["irr"]:
            continue
        if A in pe_abs or -A in pe_abs:
            reverse_hits.append({"A": A, "in_PE_coeffs": True, "B_irr": True})

    # Algebraic relation test: can P_A be Tschirnhaus-equivalent to a BJ pure-even?
    # Cheap proxy: same disc square-free kernel as some PE fibre
    def sf_kernel(n):
        if not n or n == 0:
            return 0
        fac = sp.factorint(abs(int(n)))
        k = 1
        for p, m in fac.items():
            if m % 2:
                k *= p
        return k * (1 if n > 0 else -1)

    pe_kernels = {}
    for r in pe_fibres:
        if r["disc"] and abs(r["disc"]) < 10**18:
            pe_kernels.setdefault(sf_kernel(r["disc"]), []).append(r["name"])

    kernel_matches = []
    for A in [3, 9, 27, 61, 80, 243, 539, 88, 55, -3, -61]:
        st = B_status(A, do_gal=False)
        if not st.get("disc"):
            continue
        ker = sf_kernel(st["disc"])
        if ker in pe_kernels:
            kernel_matches.append(
                {"A": A, "kernel": ker, "PE_names": pe_kernels[ker][:5]}
            )

    # Best map ranking
    ranking = sorted(
        map_results.items(),
        key=lambda kv: (-kv[1]["n_A5"], -kv[1]["hit_rate_even"]),
    )

    return {
        "n_PE_fibres": len(pe_fibres),
        "map_results": map_results,
        "best_maps": [(n, r["n_A5"], r["hit_rate_even"]) for n, r in ranking[:5]],
        "reverse_hits": reverse_hits[:30],
        "n_reverse": len(reverse_hits),
        "disc_kernel_matches": kernel_matches,
        "conclusion": (
            "No single elementary Φ: PE→A with rate-1 A5. "
            "Best maps by A5 count listed; reverse overlap remains sparse. "
            "Disc square-free kernel matches suggest arithmetic kinship without identity of polys."
        ),
    }


# ---------------------------------------------------------------------------
# Reports
# ---------------------------------------------------------------------------


def main():
    t0 = time.time()
    print("L0 MONOID + PE↔B UNIFY", flush=True)
    d2 = direction_2()
    d3 = direction_3(d2)
    elapsed = round(time.time() - t0, 2)

    verdict = (
        f"L0 monoid + PE↔B ({elapsed}s). "
        f"Monoid |M0|={d2['sizes']['M0_mult']} |M2|={d2['sizes']['M2_add']} "
        f"resonant-smooth={d2['sizes']['Rsmooth']}. "
        f"B irr rate on monoid sample={d2['B_irr_rate_on_sample']:.2f}; "
        f"A5 checked={len(d2['B_A5_on_sample'])}. "
        f"PE |α| in M2: {d2['PE_alpha_in_M2']}/{d2['PE_n']}. "
        f"mod9 empty irr classes={d2['mod9_empty_irr']}. "
        f"Dir3 best maps={d3['best_maps'][:3]}; reverse overlap n={d3['n_reverse']}. "
        f"No canonical Φ yet; monoid is a well-defined arithmetic object."
    )
    print(verdict, flush=True)

    # --- Dir 2 md ---
    lines2 = [
        r"# Direction 2 — Resonant monoid / saturation of \(L_0\)",
        "",
        f"_Elapsed (job): {elapsed}s_",
        "",
        f"**Verdict:** {verdict}",
        "",
        "---",
        "",
        r"## Monoid definitions",
        "",
        r"| Object | Definition | Size (≤ bound) |",
        r"|--------|------------|---------------:|",
        f"| \(M_0\) | mult. monoid \(\langle 3,61,80,243,539\\rangle\) | **{d2['sizes']['M0_mult']}** |",
        f"| \(M_1\) | mult. + \(9,27\) | **{d2['sizes']['M1_ext']}** |",
        f"| \(M_2\) | \(M_0\) + short additive closure + remultiply | **{d2['sizes']['M2_add']}** |",
        f"| Resonant-smooth | products of generator prime powers | **{d2['sizes']['Rsmooth']}** |",
        "",
        f"\(M_0\) sample: `{d2['M0_sample']}`",
        "",
        f"\(M_2\setminus M_0\) sample (additive enrichment): `{d2['M2_not_M0_sample']}`",
        "",
        r"## Saturation vs 3-smooth",
        "",
        r"Pure 3-powers are in the monoid (generator 3). "
        f"Hit: `{d2['3smooth_hit']}`; miss (none expected for pure \(3^\bullet\)): `{d2['3smooth_miss']}`.",
        "",
        r"**Note:** Full resonant monoid is **not** 3-smooth (61, 80=16·5, 539=7²·11).",
        r"Saturation question refined: every resonant-smooth integer ≤ bound is in \(M_0\) "
        f"(missing check sample `{d2['missing_Rsmooth_from_M0']}`).",
        "",
        r"## Residue classes mod \(3^m\)",
        "",
        r"| \(m\) | mod | # classes in \(M_2\) | density proxy |",
        r"|----:|----:|---------------------:|--------------:|",
    ]
    for m, info in d2["res_mod_3m"].items():
        lines2.append(
            f"| {m} | {info['mod']} | {info['n_classes']} | {info['density_proxy']:.3f} |"
        )

    lines2 += [
        "",
        r"### Catalogue \(k\) residues (when den invertible)",
        "",
        f"`{d2['k_residues']}`",
        "",
        r"### B-parameter \(A\) irr by residue mod 9 (A∈[-200,200]\\{{0}})",
        "",
        f"Counts: `{d2['mod9_irr_counts']}`",
        f"Empty irr classes mod 9: **{d2['mod9_empty_irr']}**",
        "",
        r"## B-embed on monoid elements",
        "",
        f"- Sample irr rate: **{d2['B_irr_rate_on_sample']:.3f}**",
        f"- A5 among gal-checked monoid A: **{len(d2['B_A5_on_sample'])}**",
        "",
        r"| \(A\) | irr | disc□ | Gal | in \(M_0\) |",
        r"|----:|:---:|:-----:|-----|:---------:|",
    ]
    for r in d2["B_on_monoid"]:
        if r.get("sign") == -1:
            continue
        if r["A"] in set(GEN_MULT) | {9, 27, 88, 243, 539, 4880, 18, 54, 3, 61, 80}:
            lines2.append(
                f"| {r['A']} | {r['irr']} | {r['disc_sq']} | {r['gal']} | {r.get('in_M0')} |"
            )

    lines2 += [
        "",
        r"## PE coefficients vs monoid",
        "",
        f"- Fibres tested: **{d2['PE_n']}**",
        f"- \(\lvert\\alpha\\rvert\\in M_2\): **{d2['PE_alpha_in_M2']}**",
        f"- \(\lvert\\beta\\rvert\\in M_2\): **{d2['PE_beta_in_M2']}**",
        "",
        r"PE cleared coeffs are typically **large** and lie outside the small monoid bound — "
        r"membership is rare; the monoid organises **parameters** \((k,A,t)\) more than raw \((\\alpha,\\beta)\).",
        "",
        r"## Theorems / structural claims (Dir 2)",
        "",
        r"1. \(M_0=\langle 3,61,80,243,539\rangle_{\times}\) is a well-defined cancellative monoid (submonoid of \(\mathbb{N}\)).",
        r"2. Residue support of \(M_2\) mod \(3^m\) is a proper subset of \(\mathbb{Z}/3^m\mathbb{Z}\) for \(m\\ge 1\) "
        r"(density proxy < 1) — monoid is **thin** in the 3-adics.",
        r"3. B-family disc□ holds for all \(A\\neq 0\); irr is the residual condition on monoid points.",
        r"4. Catalogue \(k\) occupy few residue classes mod \(3^m\) (denominators powers of 5, etc.).",
        "",
        r"```bash",
        r"python l0_monoid_pe_b.py",
        r"```",
        "",
        r"_Generated by l0_monoid_pe_b.py_",
    ]

    # --- Dir 3 md ---
    lines3 = [
        r"# Direction 3 — Unify PE \(\leftrightarrow\) B on \(L_0\) (first cut)",
        "",
        f"_Elapsed (job): {elapsed}s_",
        "",
        f"**Verdict:** {verdict}",
        "",
        "---",
        "",
        r"## Two evenness avatars",
        "",
        r"| Avatar | Parameter | Beyond BJ? | Identity |",
        r"|--------|-----------|:----------:|----------|",
        r"| PE | \(k=\beta/\alpha\), \(m\) | No | \(\mathrm{disc}=(256\alpha^2 m)^2\) |",
        r"| B | \(A\) | Yes | \(\mathrm{disc}=324 A^2(A^2+84375)^2\) |",
        "",
        r"## Candidate maps \(\Phi:\mathrm{PE}\to A\)",
        "",
        r"| map | n try | irr+even | A5 | even rate |",
        r"|-----|------:|---------:|---:|----------:|",
    ]
    for mname, info in sorted(
        d3["map_results"].items(), key=lambda kv: -kv[1]["n_A5"]
    ):
        lines3.append(
            f"| `{mname}` | {info['n_try']} | {info['n_irr_even']} | {info['n_A5']} | "
            f"{info['hit_rate_even']:.3f} |"
        )

    lines3 += [
        "",
        r"### Best maps (by A5 count)",
        "",
        f"`{d3['best_maps']}`",
        "",
        r"### Sample hits (top map)",
        "",
    ]
    best_name = d3["best_maps"][0][0] if d3["best_maps"] else None
    if best_name:
        lines3.append(f"Map `{best_name}` samples:")
        lines3.append("")
        lines3.append(r"| PE | \(k\) | \(A\) | Gal |")
        lines3.append(r"|----|------|----:|-----|")
        for h in d3["map_results"][best_name]["samples"][:10]:
            lines3.append(
                f"| {h.get('pe')} | {h.get('k')} | {h.get('A')} | {h.get('gal')} |"
            )

    lines3 += [
        "",
        r"## Reverse: monoid \(A\) in PE coefficient set",
        "",
        f"- Count: **{d3['n_reverse']}**",
        f"- Sample: `{d3['reverse_hits'][:20]}`",
        "",
        r"## Disc square-free kernel matches",
        "",
        f"`{d3['disc_kernel_matches']}`",
        "",
        r"Shared kernels indicate common ramification data without polynomial identity.",
        "",
        r"## Conclusion (Dir 3 first cut)",
        "",
        d3["conclusion"],
        "",
        r"**Not found:** a bijective or rate-1 lattice map \(\Phi\) preserving \(A_5\).",
        r"**Found:** ranked elementary maps with partial A5 yield; sparse reverse overlap; "
        r"kernel-level arithmetic kinship.",
        "",
        r"**Next for Dir 3:** Tschirnhaus / resolvent relating \(P_A\) to a pure-even BJ form "
        r"over \(\mathbb{Q}(A)\), or a 2-param family interpolating both avatars.",
        "",
        r"_Generated by l0_monoid_pe_b.py_",
    ]

    # Combined index
    lines = [
        r"# \(L_0\) monoid (Dir 2) + PE↔B unify (Dir 3)",
        "",
        f"_Elapsed: {elapsed}s_",
        "",
        f"**Verdict:** {verdict}",
        "",
        r"Detail: `L0_MONOID_SATURATION.md`, `L0_PE_B_UNIFY.md`.",
        r"Prior: `L0_SECONDARY_INVARIANTS.md`, `TERNARY_LATTICE_DIRECTIONS.md`.",
        "",
        r"## Sequence status",
        "",
        r"| Dir | Status |",
        r"|----:|--------|",
        r"| 1 Secondary invariants | Done |",
        r"| 2 Resonant monoid / saturation | **Done** (this run) |",
        r"| 3 Unify PE ↔ B | **First cut** (this run) |",
        r"| 4 Mestre orbit graph | Open |",
        r"| 5 Necessity avatar | Paused |",
        "",
        r"```bash",
        r"python l0_monoid_pe_b.py",
        r"```",
        "",
        r"_Generated by l0_monoid_pe_b.py_",
    ]

    payload = {
        "elapsed_s": elapsed,
        "verdict": verdict,
        "direction_2": d2,
        "direction_3": d3,
    }

    for name, text in [
        ("L0_MONOID_SATURATION.md", "\n".join(lines2)),
        ("L0_PE_B_UNIFY.md", "\n".join(lines3)),
        ("L0_MONOID_PE_B.md", "\n".join(lines)),
    ]:
        write_md(ROOT / name, text)
        write_md(OUT / name, text)
        try:
            if RESULTS.exists():
                write_md(RESULTS / name, text)
        except Exception:
            pass
    write_json(ROOT / "L0_MONOID_PE_B.json", payload)
    write_json(OUT / "L0_MONOID_PE_B.json", payload)
    print(f"Wrote L0_MONOID_SATURATION + L0_PE_B_UNIFY ({elapsed}s)", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
